### ISSUE TITLE
How you change the play/pause button image on click

### ISSUE THREAD

**Issue by ms-tii** [girginkagan/RedirectActions#1]
I am unable to figure out how play/pause button's image is changed on click ?
there only one method in which you only change the selected state !!
@objc func btnPlayPauseTapped(_ sender: UIButton){
        sender.isSelected = !sender.isSelected
    }

**Comment by girginkagan** [comment]
It's being changed on storyboard file actually. Open Main.storyboard file and click on play/pause button. On the right side of xcode if you open "Attributes Inspector" you can see the "State Config" setting. If you change it to "Selected" you will see the  selected image is different than the default one. By this way easily you can handle it without any code.

**Comment by ms-tii** [comment]
Oh great thanks.
